# Generated by Django 2.2.5 on 2019-12-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/teams/'),
        ),
    ]
