# Generated by Django 2.2.5 on 2019-12-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_teams_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='picture',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='teams/'),
        ),
    ]
