# Generated by Django 2.2.5 on 2019-12-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20191229_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='picture',
            field=models.FileField(blank=True, default='default.jpg', null=True, upload_to='teams/'),
        ),
    ]
