# Generated by Django 2.2.5 on 2019-09-16 07:28

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='slug',
        ),
        migrations.AddField(
            model_name='contact',
            name='uuid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, null=True, unique=True),
        ),
    ]
