# Generated by Django 2.2.5 on 2019-09-29 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='company',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='companies_tasks', to='companies.Company'),
        ),
    ]
