# Generated by Django 2.2.5 on 2019-10-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_functor'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_transferred_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last transferred on'),
        ),
    ]
