# Generated by Django 2.2.5 on 2019-09-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(blank=True, choices=[('Followup', 'Followup'), ('Call', 'Call'), ('Session', 'Session'), ('Send email', 'Send_email'), ('Send message', 'Send_message')], max_length=50, null=True, verbose_name='task_type'),
        ),
    ]
