# Generated by Django 2.2.5 on 2019-09-30 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='companies_tasks', to='companies.Company'),
        ),
    ]
