# Generated by Django 2.2.5 on 2019-10-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_flow',
            name='is_seen',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
