# Generated by Django 2.2.5 on 2019-10-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_flow_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
